version: 2

jobs:
  tests:
    docker:
      - image: swift:5.0
    steps:
      - checkout
      - run: swift build
      - run: swift test
  build-release:
    docker:
      - image: swift:5.0
    steps:
      - checkout
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - tests
      - build-release