name: test
on:
- pull_request
jobs:
  focal:
    container:
      image: swiftlang/swift:nightly-6.0-focal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test
  thread:
    container:
      image: swiftlang/swift:nightly-6.0-focal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --sanitize=thread
  address:
    container:
      image: swiftlang/swift:nightly-6.0-focal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ASAN_OPTIONS=detect_leaks=0 swift test --sanitize=address
