name: test
on:
- pull_request
jobs:
  xenial-5-2:
    container:
      image: vapor/swift:5.2-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test
  bionic-5-2:
    container:
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test
  thread:
    container:
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --sanitize=thread
  address:
    container:
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ASAN_OPTIONS=detect_leaks=0 swift test --sanitize=address
